#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '🔨👷🔨 Styling, testing and building your project before committing 🔨👷🔨'

# Check Prettier standards
yarn check:format ||
(
    echo '❌🤢🤮❌ Prettier Check Failed. ❌🤮🤢❌
            Run yarn format, add changes and try commit again.';
    false;
)
echo '✅🤔🤔 ... Format check passed ... Checking linting  ... 🤔🤔✅'

# Check ESLint Standards
yarn lint ||
(
        echo '❌😤👋❌ ESLint Check Failed ❌👋😤❌ 
                ESLint Check Failed. Make the required changes listed, add them and commit again.'
        false; 
)
echo '✅🤔🤔 ... Lint check passed  ... Checking types... 🤔🤔✅'

# Check tsconfig standards
yarn check:types ||
(
    echo '❌🤡😂🤡❌ Failed Type check. ❌🤡😂🤡❌
            Make the required changes.'
    false;
)
echo '✅🤔🤔 ... Types check passed  ... 🤔🤔✅'


# echo '🤔🤔🤔🤔 ... Code looks good ... Trying to build ... 🤔🤔🤔🤔'

# yarn build ||
# (
#     echo '❌👷🔨❌ Next build failed ❌🔨👷❌
#             View the errors above. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅👷🔨✅ ... Committing ... ✅👷🔨✅'